# Generated by Django 5.1.4 on 2024-12-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_year', models.PositiveIntegerField()),
                ('is_borrowed', models.BooleanField(default=False)),
                ('borrower_name', models.CharField(blank=True, max_length=255, null=True)),
                ('borrow_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
